Create home and about pages
simplegoose/capstone-project-1 pull request #1
Opened 2023-01-05 19:24 UTC by simplegoose

- Create a home page and style it to match the design.
- Create an about page and style it to match the design.
- Link the pages in the header using anchor tags.
- Navigation toggle for mobile devices.
- Generate HTML for featured section dynamically.

Below is the link to my loom video.
[https://www.loom.com/share/838505d237a546f3b2f1d684b44fb3bb](Loom video)

2023-01-05 21:05 UTC, huseyinbiyik requested changes
Hi @simplegoose,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Good Readme 👌
- Linter set up well and checks pass 🟢
- JS code is DRY 🌵

## Required Changes ♻️
- Please deploy your project as on Github Pages as requested [here](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#:~:text=Deploy%20the%20project%20and%20check%20to%20make%20sure%20everything%20works%20as%20planned.) on the project requirements. And please make sure you update your Live Demo link on your Readme file.
_Check the comments under the review._

## Optional suggestions
- I think it would be better if you can change the Heading of the Readme file. You can replace it with  your project name, instead of "Microverse Readme template" ↓
<img width="854" alt="Screenshot 2023-01-05 at 10 43 08 PM" src="https://user-images.githubusercontent.com/25887253/210866978-4acb71e4-e7ca-4fac-9b38-36f77339def8.png">
- It would be amazing if you can add your live presentation to your Readme file. You will notice people watching your presentation to know you and your project.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 21:05 UTC, huseyinbiyik commented on index.html
> +						<a href="/index.html" class="__logo"><img src="./assets/images/icons/logo.png" alt="Logo icon" class="logo__image"></a>
Kindly fix the mobile navbar so the background is transparent like the design below.
<img width="883" alt="Screenshot 2023-01-05 at 10 56 45 PM" src="https://user-images.githubusercontent.com/25887253/210869094-0d249732-8689-4d96-864d-4ad63ff642ad.png">

Your design has a slightly different. ↓
<img width="416" alt="Screenshot 2023-01-05 at 10 58 46 PM" src="https://user-images.githubusercontent.com/25887253/210869250-bbf60bad-9c77-4d72-ae11-c77c4fcf7699.png">

2023-01-05 21:05 UTC, huseyinbiyik commented on about.html
> +						<img src="./assets/images/icons/facebook.png" alt="Facebook" class="social--icons">
Let's stick to the design and fix the social media icons to have identical heights. Also please make sure Facebook comes before the Twitter logo.
Your design:
<img width="238" alt="Screenshot 2023-01-05 at 11 00 39 PM" src="https://user-images.githubusercontent.com/25887253/210869625-807bcd6d-8b27-42a0-a05a-19b093e02853.png">

The provided one:
<img width="238" alt="Screenshot 2023-01-05 at 11 01 04 PM" src="https://user-images.githubusercontent.com/25887253/210869627-c793bfa6-ce06-4d5c-ad6d-70e31734470e.png">

2023-01-05 21:05 UTC, huseyinbiyik commented on about.html
> +			</div>
Kindly fix the alignment here. Both logo and copyright section have to be middle-aligned. `align-items: center` could be the possible answer. Also please decrease the font size of the copyright section to match the design provided.
<img width="393" alt="Screenshot 2023-01-05 at 11 07 38 PM" src="https://user-images.githubusercontent.com/25887253/210870870-54036466-6860-4667-9e0b-ca59ff6ebc94.png">

The provided design:
<img width="393" alt="Screenshot 2023-01-05 at 11 08 00 PM" src="https://user-images.githubusercontent.com/25887253/210870876-41f3469e-8325-4cf6-913e-89010f123dec.png">

2023-01-05 21:05 UTC, huseyinbiyik commented on index.html
> +												<img src="./assets/images/icons/program_icon_01 1.png" alt="Auction icon">
- Please add one more card here like the given design. And make sure they are all contained with a semantic `<article>` tag. Semantic tags have a significant role in the SEO of the webpage.
-  Please fix the alignment of your articles, images/icon and title doesn't look aligned well. 
The provided design:
<img width="829" alt="Screenshot 2023-01-05 at 11 19 23 PM" src="https://user-images.githubusercontent.com/25887253/210872689-8edf89f3-77e0-43cc-90da-8eebae0a72c7.png">
<img width="1231" alt="Screenshot 2023-01-05 at 11 19 33 PM" src="https://user-images.githubusercontent.com/25887253/210873836-7b46732e-77c7-40d2-b5c2-8db1f68a128c.png">

2023-01-05 21:05 UTC, huseyinbiyik commented on index.html
> +							<div class="right">
Please make sure the speaker section is completely generated dynamically with JavaScript and each speaker/car has a wrapped semantic tag `<article>`.

2023-01-05 21:05 UTC, huseyinbiyik commented on about.html
> +								<h2 class="website__title">ONLINE CAR SELLERS WEBSITE</h2>
Kindly use h1 element for this heading, it is the most important element defining the web page, so it would be semantically more correct. Just swap the h1 and h2, and you are good to go. 👍

2023-01-05 21:05 UTC, huseyinbiyik commented on index.html
> +								<h2 class="website__title">ONLINE CAR SELLERS WEBSITE</h2>
Kindly use h1 element for this heading, it is the most important element defining the web page, so it would be semantically more correct. Just swap the h1 and h2, and you are good to go. 👍

2023-01-05 21:05 UTC, huseyinbiyik commented on js/index.js
> +            <div class="left"><img src="${item.imgSrc}" alt="Featured" class="featured"></div>
Please add one more property called `alt` for each image in featuredData array and add the alt attribute for each image. As you know, it has a crucial role on the accessibility of your web page, especially for people who have visual impairments.

2023-01-06 09:26 UTC, OyePriscilla requested changes
Hi @simplegoose 😃, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)


## Suggested changes

- [ ] Please ensure you deploy your app on Github pages as suggested earlier and don't forget to add it to the Readme file. This will give your repo a more professional touch, kindly go through this short [tutorial](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site). ℹ️ 

>  

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-06 09:26 UTC, OyePriscilla commented on index.html
> +												<img src="./assets/images/icons/program_icon_01 1.png" alt="Auction icon">
- [ ] One more thing to fix and you are good to go! Kindly adjust all the articles to be on the same line for good user interaction. 👍 

## Your Design at the moment

![png-transparent-nigerian-naira-currency-symbol-symbol-miscellaneous-angle-text-removebg-preview (1)](https://user-images.githubusercontent.com/103386183/210970982-7dc8992c-01f6-4c60-947c-4a58c85d0496.png)

2023-01-06 10:12 UTC, jerryowusu approved these changes
Hi @simplegoose , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200w](https://user-images.githubusercontent.com/65233860/210979940-a795f0a2-72bf-4afe-bb50-1b4b473ab8a2.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 10:47 UTC, merged